cluster-config: "/rds/project/rd109/rds-rd109-durbin-group/projects/cichlid/Bettina/data/Mzebra_UMD2a_vcf/profile/cluster.yaml"
cluster: "sbatch --job-name={cluster.jobname} --nodes={cluster.nodes} --ntasks-per-node={cluster.ntaskspernode} --cpus-per-task={cluster.cpuspertask} --time={cluster.time} --account={cluster.account} --partition={cluster.partition} --mail-type={cluster.mailtype} --output={cluster.output} --export=ALL "
jobs: 99998
verbose: true
notemp: false